### ISSUE TITLE
Create slides for the presentation

### ISSUE THREAD

**Issue by mlanuri10** [xlab-classes/cse442-spring2022-team-pyc442#104]
**Task Test**

*Test 1*

1. Create slides for the presentation
2. For each slide, do the following:
- What is the motivation of the project and what is the objective?

- What techniques you are using for the project and what solutions you (as a team) are trying to solve?

- What tasks that you have made so far?

- Analyze what you did during the project

- What are the final plans for the project?

3. Modify the slides

**Comment by seongjae20** [comment]
Test and dependency.

**Comment by seongjae20** [comment]
Need test and dependency.
