### ISSUE TITLE
Display the list of added users via scroll bar

### ISSUE THREAD

**Issue by Icelunary** [xlab-classes/cse442-spring2022-team-pyc442#105]
**Task Test**

*Test 1:* Displayed added users

1) Login as admin with username = "admin" password = "password" and click login
2) Navigate to add user page
3) Add user/users with username and password which are up to you.
4) Check the added users are displayed on the page (This is the only frontend. Must be accompanied by backend)

*Test 2:* Kick a user
1) Select a user
2) Click "kick/remove" button
3) Make sure the kicked users are not displayed and can't login

**Comment by seongjae20** [comment]
Need dependency
