### ISSUE TITLE
Change user information and remove user from the database

### ISSUE THREAD

**Issue by mrtrayno** [xlab-classes/cse442-spring2022-team-pyc442#26]
**Task Tests**

*Test 1*
1) Select a user currently in the database
2) Write queries to modify a user's information:
    - change username/password
    - change blocked status
3) Verify that the information was modified correctly

*Test 2*
1) Create a new user
2) Add them to the database
3) Write queries to delete them from the database
4) Verify that the user was successfully removed

**Comment by mlanuri10** [comment]
Test 1:
1. queries()
2. UPDATE wireguard SET email = (new email), password = (new password) where user_id = id
3. cnx.commit() after 2.
4. queries()

Test 2
1. add_users()
2. DELETE FROM wireguard WHERE (email, username, or id) = just added
3. cnx.commit() after 2
3. queries()

**Comment by mrtrayno** [comment]
Change deleteTuple so that it only deletes one tuple specified by uid

**Comment by mrtrayno** [comment]
modifyUsername and changeBannedStatus now working, just need to finish and test deleteTuple

**Comment by mlanuri10** [comment]
Tested and completed.
