### ISSUE TITLE
Finish necessary functtion and queries for database

### ISSUE THREAD

**Issue by mrtrayno** [xlab-classes/cse442-spring2022-team-pyc442#28]
**Task Test**

*Test 1*
1) Finish the following functions;
-find user by name
-find user by id
-find if user's name exists
2) Write the appropriate queries for these functions
3) Test to make sure these work correctly

**Comment by mlanuri10** [comment]
-find user by name
SELECT * FROM wireguard WHERE username = name

-find user by id
SELECT * FROM wireguard WHERE user_id = id

-find if user's name exists
SELECT * FROM wireguard WHERE username == name (I think.)

**Comment by mrtrayno** [comment]
Checking if user exists can be done by checking if query returns NULL
