### ISSUE TITLE
Create wireguard server

### ISSUE THREAD

**Issue by animalman33** [xlab-classes/cse442-spring2022-team-pyc442#64]
**Task Tests**

*Test 1*
1. Press start button on admin dashboard
2. check to see if wireguard server has been started (ps aux | grep wireguard)

*Test 2*
1. Press stop button on admin dashboard
2. check to see if wireguard server has been stopped (ps aux | grep wireguard)

**Comment by seongjae20** [comment]
Task tests is italic and test 1 and 2 are bold. They are reversed.

**Comment by animalman33** [comment]
Fixed
